// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// C++ from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


#include "OI.h"

// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=INCLUDES
#include "SmartDashboard/SmartDashboard.h"
#include "Commands/AutonomouseGroup1.h"
#include "Commands/MoveArmCommand.h"
#include "Commands/MoveDistanceCommand.h"
#include "Commands/MoveKickerCommand.h"
#include "Commands/ShootCommand.h"
#include "Commands/TankDriveCommand.h"
#include "Commands/TurnCommand.h"


    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=INCLUDES

OI::OI() {
    // Process operator interface input here.
    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS
    robotOperator.reset(new Joystick(1));
    

    driver.reset(new Joystick(0));

    // SmartDashboard Buttons
    SmartDashboard::PutData("MoveKickerCommand", new MoveKickerCommand());
    SmartDashboard::PutData("ShootCommand", new ShootCommand());
    SmartDashboard::PutData("TurnCommand", new TurnCommand());
    SmartDashboard::PutData("MoveDistanceCommand", new MoveDistanceCommand());
    SmartDashboard::PutData("AutonomouseGroup1", new AutonomouseGroup1());
    SmartDashboard::PutData("MoveArmCommand", new MoveArmCommand());
    SmartDashboard::PutData("TankDriveCommand", new TankDriveCommand());

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS
}

// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=FUNCTIONS

std::shared_ptr<Joystick> OI::getDriver() {
   return driver;
}

std::shared_ptr<Joystick> OI::getRobotOperator() {
   return robotOperator;
}


    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=FUNCTIONS
