// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// C++ from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


#include "RobotMap.h"
#include "LiveWindow/LiveWindow.h"


// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=ALLOCATION
std::shared_ptr<SpeedController> RobotMap::driveTrainLeftMotor;
std::shared_ptr<SpeedController> RobotMap::driveTrainRightMotor;
std::shared_ptr<RobotDrive> RobotMap::driveTrainDriveMotors;

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=ALLOCATION

void RobotMap::init() {
    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS
    LiveWindow *lw = LiveWindow::GetInstance();

    driveTrainLeftMotor.reset(new VictorSP(0));
    lw->AddActuator("DriveTrain", "LeftMotor", (VictorSP&) driveTrainLeftMotor);
    
    driveTrainRightMotor.reset(new VictorSP(1));
    lw->AddActuator("DriveTrain", "RightMotor", (VictorSP&) driveTrainRightMotor);
    
    driveTrainDriveMotors.reset(new RobotDrive(driveTrainLeftMotor, driveTrainRightMotor));
    
    driveTrainDriveMotors->SetSafetyEnabled(false);
        driveTrainDriveMotors->SetExpiration(0.1);
        driveTrainDriveMotors->SetSensitivity(0.5);
        driveTrainDriveMotors->SetMaxOutput(1.0);



    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS
}
